version: '3'
services:
  mysql:
    container_name: 'mysql-demo'
    image: mysql:8.0.27
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./mysql/.env
    restart: always
