spring:
  profiles.active: local
  jpa:
    hibernate.use-new-id-generator-mappings: false
    properties.hibernate.implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    show-sql: true
  application:
    name: demo

security.pbkdf2:
  iteration-count: 1000
  key-size: 128
  passphrase: ded1a2c2-9e46-43f9-8983-2faf956a9dc7
  iv: 7f5f1ccbcf7a41913fe438dd6167b66a

---
server.port: 8080
spring.profiles: local

#spring.jpa:
#  database: mysql

spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/demo?characterEncoding=utf8&useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
  username: demo
  password: '1q2w3e4r'
